### ISSUE TITLE
Backport to 1.17.1?

### ISSUE THREAD

**Issue by the-just-luke** [JustinTimeCuber/wider-stats-screen#2]

**Comment by JustinTimeCuber** [comment]
I'll look into it. But pre-1.18 MC uses Java 16, not 17, so could cause some complications.

**Comment by JustinTimeCuber** [comment]
Looks like it's a bit more involved than I thought it might be. Should be doable if someone else wants to backport it, but I don't want to maintain multiple branches currently.
